FROM python:3.13-slim

WORKDIR /app

COPY src/ /app/src/
COPY data/ /app/data/
COPY src/requirements.txt /app/requirements.txt

ENV PYTHONPATH="/app"

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "src/ingest.py"]
