FROM bde2020/spark-master:3.2.1-hadoop3.2

# MongoDB Spark Connector
ADD https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/3.0.1/mongo-spark-connector_2.12-3.0.1.jar /spark/jars/

# MongoDB Java Driver (required dependencies)
ADD https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-core/4.9.0/mongodb-driver-core-4.9.0.jar /spark/jars/
ADD https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-sync/4.9.0/mongodb-driver-sync-4.9.0.jar /spark/jars/
ADD https://repo1.maven.org/maven2/org/mongodb/bson/4.9.0/bson-4.9.0.jar /spark/jars/

# Elasticsearch Spark Connector (Spark 3.x + Scala 2.12)
ADD https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-spark-30_2.12/7.17.9/elasticsearch-spark-30_2.12-7.17.9.jar /spark/jars/
